application: minicontestorg
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /minicontest.css
  static_files: minicontest.css
  upload: minicontest.css
- url: /challenges/(new|submit|\d+/enter)
  script: main.py
  login: required
- url: /admin.*
  script: main.py
  login: admin
- url: /.*
  script: main.py
